### ISSUE TITLE
Value of type 'TaskGroup<Void>' has no member 'addTask'

### ISSUE THREAD

**Issue by karthikkumar-manian** [Actomaton/Actomaton-Gallery#4]
Value of type 'TaskGroup<Void>' has no member 'addTask'
Value of type 'TaskGroup<Void>' has no member 'waitForAll'

Getting this error while running the project on XCODE 11 Beta 3

<img width="1904" alt="Screenshot 2021-09-13 at 1 15 52 PM" src="https://user-images.githubusercontent.com/45222855/133044358-8f241482-6d2e-4293-bd94-19aa47bf792a.png">

**Comment by inamiy** [comment]
Code will compile as of Xcode 13.
