### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by tomisacat** [Actomaton/Actomaton-Gallery#45]
After clone the repo, update and pre-fetch packages in terminal:

```
$> swift package update
$> xcodebuild -resolvePackageDependencies -scmProvider system
```

Then, open the Package file:

```
$> open Package.swift
```

After Xcode popup, select scheme `SwiftUI-Gallery` with `iPhone 13` simulator and hit run button, error happens: 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/1179735/182650585-cf86d044-904b-4e3d-9c7c-6eb6e6591c65.png">
 
Is there some steps I missed or something else?

**Comment by inamiy** [comment]
Example projects are in `Examples` folder,
e.g. https://github.com/Actomaton/Actomaton-Gallery/tree/main/Examples/SwiftUI-Gallery

And basically you need to open Xcode's xcodeproj.
